# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage-badge pytest coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate coverage badge
      run: |
        coverage run -m pytest
        coverage-badge -o coverage.svg -f
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: CI add coverage badge

